// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalargalaxy

import (
	"context"
	"net/http"
	"slices"

	"scalar-galaxy/internal/apijson"
	"scalar-galaxy/internal/param"
	"scalar-galaxy/internal/requestconfig"
	"scalar-galaxy/option"
)

// AuthenticationService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewAuthenticationService] method instead.
type AuthenticationService struct {
	Options []option.RequestOption
}

// NewAuthenticationService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewAuthenticationService(opts ...option.RequestOption) (r *AuthenticationService) {
	r = &AuthenticationService{}
	r.Options = opts
	return
}

// Time to create a user account, eh?
//
// Parameters:
//     ctx: Context for the request.
//     body: AuthenticationNewUserParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *User: User account created successfully
//
// Example:
//
//     authentication, err := client.Authentication.NewUser(context.Background(), sdk.AuthenticationNewUserParams{
//     	Email: sdk.F[string]("marc@scalar.com"),
//     	Password: sdk.F[string]("i-love-scalar"),
//     	Name: sdk.F[string]("Marc"),
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(authentication)
func (r *AuthenticationService) NewUser(ctx context.Context, body AuthenticationNewUserParams, opts ...option.RequestOption) (res *User, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "user/signup"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Yeah, this is the boring security stuff. Just get your super secret token and move on.
//
// Parameters:
//     ctx: Context for the request.
//     body: AuthenticationNewTokenParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *AuthenticationNewTokenResponse: Token Created
//
// Example:
//
//     authentication, err := client.Authentication.NewToken(context.Background(), sdk.AuthenticationNewTokenParams{
//     	Credentials: sdk.CredentialsParam{
//     	Email: sdk.F[string]("marc@scalar.com"),
//     	Password: sdk.F[string]("i-love-scalar"),
//     },
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(authentication)
func (r *AuthenticationService) NewToken(ctx context.Context, body AuthenticationNewTokenParams, opts ...option.RequestOption) (res *AuthenticationNewTokenResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "auth/token"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Find yourself they say. That's what you can do here.
//
// Parameters:
//     ctx: Context for the request.
//     opts: Options to apply to this request.
//
// Returns:
//     *User: Authenticated user information retrieved successfully
//
// Example:
//
//     authentication, err := client.Authentication.ListMe(context.Background())
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(authentication)
func (r *AuthenticationService) ListMe(ctx context.Context, opts ...option.RequestOption) (res *User, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "me"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type User struct {
	ID int64 `json:"id"`
	Name string `json:"name"`
	JSON userJSON `json:"-"`
}

// userJSON contains the JSON metadata for the struct [User]
type userJSON struct {
	ID apijson.Field
	Name apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *User) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r userJSON) RawJSON() string {
	return r.raw
}

type UserParam struct {
	Name param.Field[string] `json:"name"`
}

func (r UserParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type CredentialsParam struct {
	Email param.Field[string] `json:"email" api:"required" format:"email"`
	Password param.Field[string] `json:"password" api:"required"`
}

func (r CredentialsParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type AuthenticationNewTokenResponse struct {
	Token string `json:"token"`
	JSON authenticationNewTokenResponseJSON `json:"-"`
}

// authenticationNewTokenResponseJSON contains the JSON metadata for the struct [AuthenticationNewTokenResponse]
type authenticationNewTokenResponseJSON struct {
	Token apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *AuthenticationNewTokenResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r authenticationNewTokenResponseJSON) RawJSON() string {
	return r.raw
}

type AuthenticationNewUserParams struct {
	Email param.Field[string] `json:"email" api:"required" format:"email"`
	Password param.Field[string] `json:"password" api:"required"`
	Name param.Field[string] `json:"name"`
}

func (r AuthenticationNewUserParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type AuthenticationNewTokenParams struct {
	Credentials CredentialsParam `json:"credentials" api:"required"`
}

func (r AuthenticationNewTokenParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.Credentials)
}
