// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalargalaxy

import (
	"context"
	"net/http"
	"reflect"
	"slices"
	"time"

	"github.com/tidwall/gjson"

	"github.com/scalar/galaxy-go/internal/apijson"
	"github.com/scalar/galaxy-go/internal/param"
	"github.com/scalar/galaxy-go/internal/requestconfig"
	"github.com/scalar/galaxy-go/option"
)

// CelestialBodyService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewCelestialBodyService] method instead.
type CelestialBodyService struct {
	Options []option.RequestOption
}

// NewCelestialBodyService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewCelestialBodyService(opts ...option.RequestOption) (r *CelestialBodyService) {
	r = &CelestialBodyService{}
	r.Options = opts
	return
}

// Stars, moons, comets, the occasional rogue asteroid — if it glows or drifts through the void, you can add it here.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: CelestialBodyNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*CelestialBody: Celestial body created
//
// Example:
//
//	celestialBody, err := client.CelestialBodies.New(context.Background(), sdk.CelestialBodyNewParams{
//		CelestialBody: sdk.PlanetParam{
//			Name: sdk.F[string]("Mars"),
//		},
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(celestialBody)
func (r *CelestialBodyService) New(ctx context.Context, body CelestialBodyNewParams, opts ...option.RequestOption) (res *CelestialBody, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "celestial-bodies"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

type CelestialBodyNewParams struct {
	CelestialBody CelestialBodyUnionParam `json:"celestial_body" api:"required"`
}

func (r CelestialBodyNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.CelestialBody)
}

type CelestialBody struct {
	Name string `json:"name" api:"required"`
	ID   int64  `json:"id"`
	// Atmospheric composition
	Atmosphere interface{} `json:"atmosphere"`
	// A user
	Creator     User   `json:"creator"`
	Description string `json:"description" api:"nullable"`
	// Diameter in kilometers
	Diameter     float64   `json:"diameter"`
	DiscoveredAt time.Time `json:"discoveredAt" format:"date-time"`
	// URL which gets invoked upon a failed operation
	FailureCallbackURL string `json:"failureCallbackUrl" format:"uri"`
	// A score from 0 to 1 indicating potential habitability
	HabitabilityIndex  float64     `json:"habitabilityIndex"`
	Image              string      `json:"image" api:"nullable"`
	LastUpdated        time.Time   `json:"lastUpdated" format:"date-time"`
	Orbit              interface{} `json:"orbit"`
	PhysicalProperties interface{} `json:"physicalProperties"`
	Satellites         interface{} `json:"satellites"`
	// URL which gets invoked upon a successful operation
	SuccessCallbackURL string            `json:"successCallbackUrl" format:"uri"`
	Tags               interface{}       `json:"tags"`
	Type               CelestialBodyType `json:"type"`
	JSON               celestialBodyJSON `json:"-"`
	union              CelestialBodyUnion
}

// celestialBodyJSON contains the JSON metadata for the struct [CelestialBody]
type celestialBodyJSON struct {
	Name               apijson.Field
	ID                 apijson.Field
	Atmosphere         apijson.Field
	Creator            apijson.Field
	Description        apijson.Field
	Diameter           apijson.Field
	DiscoveredAt       apijson.Field
	FailureCallbackURL apijson.Field
	HabitabilityIndex  apijson.Field
	Image              apijson.Field
	LastUpdated        apijson.Field
	Orbit              apijson.Field
	PhysicalProperties apijson.Field
	Satellites         apijson.Field
	SuccessCallbackURL apijson.Field
	Tags               apijson.Field
	Type               apijson.Field
	raw                string
	ExtraFields        map[string]apijson.Field
}

func (r celestialBodyJSON) RawJSON() string {
	return r.raw
}

func (r *CelestialBody) UnmarshalJSON(data []byte) (err error) {
	*r = CelestialBody{}
	err = apijson.UnmarshalRoot(data, &r.union)
	if err != nil {
		return err
	}
	return apijson.Port(r.union, &r)
}

func (r CelestialBody) AsUnion() CelestialBodyUnion {
	return r.union
}

type CelestialBodyParam struct {
	Name               param.Field[string]            `json:"name" api:"required"`
	Atmosphere         param.Field[interface{}]       `json:"atmosphere"`
	Creator            param.Field[UserParam]         `json:"creator"`
	Description        param.Field[string]            `json:"description"`
	Diameter           param.Field[float64]           `json:"diameter"`
	DiscoveredAt       param.Field[time.Time]         `json:"discoveredAt" format:"date-time"`
	FailureCallbackURL param.Field[string]            `json:"failureCallbackUrl" format:"uri"`
	HabitabilityIndex  param.Field[float64]           `json:"habitabilityIndex"`
	Image              param.Field[string]            `json:"image"`
	Orbit              param.Field[interface{}]       `json:"orbit"`
	PhysicalProperties param.Field[interface{}]       `json:"physicalProperties"`
	Satellites         param.Field[interface{}]       `json:"satellites"`
	SuccessCallbackURL param.Field[string]            `json:"successCallbackUrl" format:"uri"`
	Tags               param.Field[interface{}]       `json:"tags"`
	Type               param.Field[CelestialBodyType] `json:"type"`
}

func (r CelestialBodyParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

func (r CelestialBodyParam) implementsCelestialBodyUnionParam() {}

// Satisfied by [PlanetParam], [CelestialBodySatelliteParam], [CelestialBodyParam].
type CelestialBodyUnionParam interface {
	implementsCelestialBodyUnionParam()
}

func (r PlanetParam) implementsCelestialBodyUnionParam() {}

func (r CelestialBodySatelliteParam) implementsCelestialBodyUnionParam() {}

type CelestialBodyUnion interface {
	implementsCelestialBody()
}

func init() {
	apijson.RegisterUnion(
		reflect.TypeOf((*CelestialBodyUnion)(nil)).Elem(),
		"",
		apijson.UnionVariant{
			TypeFilter: gjson.JSON,
			Type:       reflect.TypeOf(Planet{}),
		},
		apijson.UnionVariant{
			TypeFilter: gjson.JSON,
			Type:       reflect.TypeOf(CelestialBodySatellite{}),
		},
	)
}

type CelestialBodyType string

const (
	CelestialBodyTypeTerrestrial CelestialBodyType = "terrestrial"
	CelestialBodyTypeGasGiant    CelestialBodyType = "gas_giant"
	CelestialBodyTypeIceGiant    CelestialBodyType = "ice_giant"
	CelestialBodyTypeDwarf       CelestialBodyType = "dwarf"
	CelestialBodyTypeSuperEarth  CelestialBodyType = "super_earth"
	CelestialBodyTypeMoon        CelestialBodyType = "moon"
	CelestialBodyTypeAsteroid    CelestialBodyType = "asteroid"
	CelestialBodyTypeComet       CelestialBodyType = "comet"
)

func (r CelestialBodyType) IsKnown() bool {
	switch r {
	case CelestialBodyTypeTerrestrial, CelestialBodyTypeGasGiant, CelestialBodyTypeIceGiant, CelestialBodyTypeDwarf, CelestialBodyTypeSuperEarth, CelestialBodyTypeMoon, CelestialBodyTypeAsteroid, CelestialBodyTypeComet:
		return true
	}
	return false
}

type CelestialBodySatelliteParam struct {
	Name        param.Field[string] `json:"name" api:"required"`
	Description param.Field[string] `json:"description"`
	// Diameter in kilometers
	Diameter param.Field[float64]                    `json:"diameter"`
	Orbit    param.Field[interface{}]                `json:"orbit"`
	Type     param.Field[CelestialBodySatelliteType] `json:"type"`
}

func (r CelestialBodySatelliteParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

func (r Planet) implementsCelestialBody() {}

type CelestialBodySatellite struct {
	Name        string `json:"name" api:"required"`
	ID          int64  `json:"id"`
	Description string `json:"description" api:"nullable"`
	// Diameter in kilometers
	Diameter float64                    `json:"diameter"`
	Orbit    interface{}                `json:"orbit"`
	Type     CelestialBodySatelliteType `json:"type"`
	JSON     celestialBodySatelliteJSON `json:"-"`
}

// celestialBodySatelliteJSON contains the JSON metadata for the struct [CelestialBodySatellite]
type celestialBodySatelliteJSON struct {
	Name        apijson.Field
	ID          apijson.Field
	Description apijson.Field
	Diameter    apijson.Field
	Orbit       apijson.Field
	Type        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *CelestialBodySatellite) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r celestialBodySatelliteJSON) RawJSON() string {
	return r.raw
}

func (r CelestialBodySatellite) implementsCelestialBody() {}

type CelestialBodySatelliteType string

const (
	CelestialBodySatelliteTypeMoon     CelestialBodySatelliteType = "moon"
	CelestialBodySatelliteTypeAsteroid CelestialBodySatelliteType = "asteroid"
	CelestialBodySatelliteTypeComet    CelestialBodySatelliteType = "comet"
)

func (r CelestialBodySatelliteType) IsKnown() bool {
	switch r {
	case CelestialBodySatelliteTypeMoon, CelestialBodySatelliteTypeAsteroid, CelestialBodySatelliteTypeComet:
		return true
	}
	return false
}
