// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalargalaxy

import (
	"context"
	"net/http"
	"os"
	"slices"
	"strings"

	"github.com/scalar/galaxy-go/internal/requestconfig"
	"github.com/scalar/galaxy-go/option"
)

// Client creates a struct with services and top level methods that help with
// interacting with the Scalar Galaxy API. You should not instantiate this client
// directly, and instead use the [NewClient] method instead.
type Client struct {
	Options         []option.RequestOption
	Planets         *PlanetService
	CelestialBodies *CelestialBodyService
	Authentication  *AuthenticationService
	Webhooks        *WebhookService
}

// DefaultClientOptions read from the environment. This should be used to initialize
// new clients.
func DefaultClientOptions() []option.RequestOption {
	defaults := []option.RequestOption{option.WithHTTPClient(defaultHTTPClient()), option.WithEnvironmentProduction()}
	if o, ok := os.LookupEnv("SCALAR_BASE_URL"); ok {
		defaults = append(defaults, option.WithBaseURL(o))
	}
	if o, ok := os.LookupEnv("BEARER_AUTH"); ok {
		defaults = append(defaults, option.WithBearerAuth(o))
	}
	if o, ok := os.LookupEnv("BASIC_AUTH_USERNAME"); ok {
		defaults = append(defaults, option.WithBasicAuthUsername(o))
	}
	if o, ok := os.LookupEnv("BASIC_AUTH_PASSWORD"); ok {
		defaults = append(defaults, option.WithBasicAuthPassword(o))
	}
	if o, ok := os.LookupEnv("API_KEY_HEADER"); ok {
		defaults = append(defaults, option.WithAPIKeyHeader(o))
	}
	if o, ok := os.LookupEnv("API_KEY_QUERY"); ok {
		defaults = append(defaults, option.WithAPIKeyQuery(o))
	}
	if o, ok := os.LookupEnv("API_KEY_COOKIE"); ok {
		defaults = append(defaults, option.WithAPIKeyCookie(o))
	}
	if o, ok := os.LookupEnv("SCALAR_WEBHOOK_SECRET"); ok && o != "" {
		defaults = append(defaults, option.WithWebhookSecret(o))
	}
	if o, ok := os.LookupEnv("SCALAR_CUSTOM_HEADERS"); ok {
		for _, line := range strings.Split(o, "\n") {
			colon := strings.Index(line, ":")
			if colon >= 0 {
				defaults = append(defaults, option.WithHeader(strings.TrimSpace(line[:colon]), strings.TrimSpace(line[colon+1:])))
			}
		}
	}
	return defaults
}

// NewClient generates a new client with the default option read from the
// environment. The option passed in as arguments are applied after these default
// arguments, and all option will be passed down to the services and requests that
// this client makes.
func NewClient(opts ...option.RequestOption) (r *Client) {
	opts = append(DefaultClientOptions(), opts...)

	r = &Client{Options: opts}

	r.Planets = NewPlanetService(opts...)
	r.CelestialBodies = NewCelestialBodyService(opts...)
	r.Authentication = NewAuthenticationService(opts...)
	r.Webhooks = NewWebhookService(opts...)

	return
}

// Execute makes a request with the given context, method, URL, request params,
// response, and request options.
func (r *Client) Execute(ctx context.Context, method string, path string, params interface{}, res interface{}, opts ...option.RequestOption) error {
	opts = slices.Concat(r.Options, opts)
	return requestconfig.ExecuteNewRequest(ctx, method, path, params, res, opts...)
}

// Get makes a GET request with the given URL, params, and optionally
// deserializes to a response. See [Execute] documentation on the params and response.
func (r *Client) Get(ctx context.Context, path string, params interface{}, res interface{}, opts ...option.RequestOption) error {
	return r.Execute(ctx, http.MethodGet, path, params, res, opts...)
}

// Post makes a POST request with the given URL, params, and optionally
// deserializes to a response. See [Execute] documentation on the params and response.
func (r *Client) Post(ctx context.Context, path string, params interface{}, res interface{}, opts ...option.RequestOption) error {
	return r.Execute(ctx, http.MethodPost, path, params, res, opts...)
}

// Put makes a PUT request with the given URL, params, and optionally
// deserializes to a response. See [Execute] documentation on the params and response.
func (r *Client) Put(ctx context.Context, path string, params interface{}, res interface{}, opts ...option.RequestOption) error {
	return r.Execute(ctx, http.MethodPut, path, params, res, opts...)
}

// Patch makes a PATCH request with the given URL, params, and optionally
// deserializes to a response. See [Execute] documentation on the params and response.
func (r *Client) Patch(ctx context.Context, path string, params interface{}, res interface{}, opts ...option.RequestOption) error {
	return r.Execute(ctx, http.MethodPatch, path, params, res, opts...)
}

// Delete makes a DELETE request with the given URL, params, and optionally
// deserializes to a response. See [Execute] documentation on the params and response.
func (r *Client) Delete(ctx context.Context, path string, params interface{}, res interface{}, opts ...option.RequestOption) error {
	return r.Execute(ctx, http.MethodDelete, path, params, res, opts...)
}
