// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalargalaxy

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/scalar/galaxy-go/internal/apiform"
	"github.com/scalar/galaxy-go/internal/apijson"
	"github.com/scalar/galaxy-go/internal/apiquery"
	"github.com/scalar/galaxy-go/internal/param"
	"github.com/scalar/galaxy-go/internal/requestconfig"
	"github.com/scalar/galaxy-go/option"
)

// PlanetService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewPlanetService] method instead.
type PlanetService struct {
	Options []option.RequestOption
}

// NewPlanetService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewPlanetService(opts ...option.RequestOption) (r *PlanetService) {
	r = &PlanetService{}
	r.Options = opts
	return
}

// It's easy to say you know them all, but do you really? Retrieve all the planets and check whether you missed one.
//
// Parameters:
//     ctx: Context for the request.
//     query: PlanetListAllDataParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *PlanetListAllDataResponse: OK
//
// Example:
//
//     planet, err := client.Planets.ListAllData(context.Background(), sdk.PlanetListAllDataParams{
//     	Limit: sdk.F[int64](10),
//     	Offset: sdk.F[int64](0),
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(planet)
func (r *PlanetService) ListAllData(ctx context.Context, query PlanetListAllDataParams, opts ...option.RequestOption) (res *PlanetListAllDataResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "planets"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Time to play god and create a new planet. What do you think? Ah, don't think too much. What could go wrong anyway?
//
// Parameters:
//     ctx: Context for the request.
//     body: PlanetNewParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *Planet: Created
//
// Example:
//
//     planet, err := client.Planets.New(context.Background(), sdk.PlanetNewParams{
//     	Planet: sdk.PlanetParam{
//     	Name: sdk.F[string]("Mars"),
//     },
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(planet)
func (r *PlanetService) New(ctx context.Context, body PlanetNewParams, opts ...option.RequestOption) (res *Planet, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "planets"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// You'll better learn a little bit more about the planets. It might come in handy once space travel is available for everyone.
//
// Parameters:
//     ctx: Context for the request.
//     planetID: The ID of the planet to get
//     opts: Options to apply to this request.
//
// Returns:
//     *Planet: Planet Found
//
// Example:
//
//     planet, err := client.Planets.Get(context.Background(), 1)
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(planet)
func (r *PlanetService) Get(ctx context.Context, planetID int64, opts ...option.RequestOption) (res *Planet, err error) {
	opts = slices.Concat(r.Options, opts)
	path := fmt.Sprintf("planets/%v", planetID)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Sometimes you make mistakes, that's fine. No worries, you can update all planets.
//
// Parameters:
//     ctx: Context for the request.
//     planetID: The ID of the planet to get
//     body: PlanetUpdateParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *Planet: Planet updated successfully
//
// Example:
//
//     planet, err := client.Planets.Update(context.Background(), 1, sdk.PlanetUpdateParams{
//     	Planet: sdk.PlanetParam{
//     	Name: sdk.F[string]("Mars"),
//     },
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(planet)
func (r *PlanetService) Update(ctx context.Context, planetID int64, body PlanetUpdateParams, opts ...option.RequestOption) (res *Planet, err error) {
	opts = slices.Concat(r.Options, opts)
	path := fmt.Sprintf("planets/%v", planetID)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, path, body, &res, opts...)
	return res, err
}

// This endpoint was used to delete planets. Unfortunately, that caused a lot of trouble for planets with life. So, this endpoint is now deprecated and should not be used anymore.
//
// Parameters:
//     ctx: Context for the request.
//     planetID: The ID of the planet to get
//     opts: Options to apply to this request.
//
// Returns:
//     error: No Content
//
// Example:
//
//     err := client.Planets.Delete(context.Background(), 1)
//     if err != nil {
//     	panic(err)
//     }
func (r *PlanetService) Delete(ctx context.Context, planetID int64, opts ...option.RequestOption) (err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "*/*")}, opts...)
	path := fmt.Sprintf("planets/%v", planetID)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, nil, opts...)
	return err
}

// Got a crazy good photo of a planet? Share it with the world!
//
// Parameters:
//     ctx: Context for the request.
//     planetID: The ID of the planet to get
//     body: PlanetUploadImageParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *PlanetUploadImageResponse: Image uploaded
//
// Example:
//
//     planet, err := client.Planets.UploadImage(context.Background(), 1, sdk.PlanetUploadImageParams{})
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(planet)
func (r *PlanetService) UploadImage(ctx context.Context, planetID int64, body PlanetUploadImageParams, opts ...option.RequestOption) (res *PlanetUploadImageResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := fmt.Sprintf("planets/%v/image", planetID)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

type Planet struct {
	ID int64 `json:"id" api:"required"`
	Name string `json:"name" api:"required"`
	Description string `json:"description" api:"nullable"`
	Type PlanetType `json:"type"`
	// A score from 0 to 1 indicating potential habitability
	HabitabilityIndex float64 `json:"habitabilityIndex"`
	PhysicalProperties PlanetPhysicalProperties `json:"physicalProperties"`
	// Atmospheric composition
	Atmosphere []PlanetAtmosphere `json:"atmosphere"`
	DiscoveredAt time.Time `json:"discoveredAt" format:"date-time"`
	Image string `json:"image" api:"nullable"`
	Satellites []*Satellite `json:"satellites"`
	// A user
	Creator User `json:"creator"`
	Tags []string `json:"tags"`
	LastUpdated time.Time `json:"lastUpdated" format:"date-time"`
	// URL which gets invoked upon a successful operation
	SuccessCallbackURL string `json:"successCallbackUrl" format:"uri"`
	// URL which gets invoked upon a failed operation
	FailureCallbackURL string `json:"failureCallbackUrl" format:"uri"`
	JSON planetJSON `json:"-"`
}

// planetJSON contains the JSON metadata for the struct [Planet]
type planetJSON struct {
	ID apijson.Field
	Name apijson.Field
	Description apijson.Field
	Type apijson.Field
	HabitabilityIndex apijson.Field
	PhysicalProperties apijson.Field
	Atmosphere apijson.Field
	DiscoveredAt apijson.Field
	Image apijson.Field
	Satellites apijson.Field
	Creator apijson.Field
	Tags apijson.Field
	LastUpdated apijson.Field
	SuccessCallbackURL apijson.Field
	FailureCallbackURL apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Planet) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r planetJSON) RawJSON() string {
	return r.raw
}

type PlanetParam struct {
	Name param.Field[string] `json:"name" api:"required"`
	// Atmospheric composition
	Atmosphere param.Field[[]PlanetAtmosphereParam] `json:"atmosphere"`
	// A user
	Creator param.Field[UserParam] `json:"creator"`
	Description param.Field[string] `json:"description"`
	DiscoveredAt param.Field[time.Time] `json:"discoveredAt" format:"date-time"`
	// URL which gets invoked upon a failed operation
	FailureCallbackURL param.Field[string] `json:"failureCallbackUrl" format:"uri"`
	// A score from 0 to 1 indicating potential habitability
	HabitabilityIndex param.Field[float64] `json:"habitabilityIndex"`
	Image param.Field[string] `json:"image"`
	PhysicalProperties param.Field[PlanetPhysicalPropertiesParam] `json:"physicalProperties"`
	Satellites param.Field[[]*SatelliteParam] `json:"satellites"`
	// URL which gets invoked upon a successful operation
	SuccessCallbackURL param.Field[string] `json:"successCallbackUrl" format:"uri"`
	Tags param.Field[[]string] `json:"tags"`
	Type param.Field[PlanetType] `json:"type"`
}

func (r PlanetParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type PlanetType string

const (
	PlanetTypeTerrestrial PlanetType = "terrestrial"
	PlanetTypeGasGiant PlanetType = "gas_giant"
	PlanetTypeIceGiant PlanetType = "ice_giant"
	PlanetTypeDwarf PlanetType = "dwarf"
	PlanetTypeSuperEarth PlanetType = "super_earth"
)

func (r PlanetType) IsKnown() bool {
	switch r {
	case PlanetTypeTerrestrial, PlanetTypeGasGiant, PlanetTypeIceGiant, PlanetTypeDwarf, PlanetTypeSuperEarth:
		return true
	}
	return false
}

type Satellite struct {
	Name string `json:"name" api:"required"`
	ID int64 `json:"id"`
	Description string `json:"description" api:"nullable"`
	// Diameter in kilometers
	Diameter float64 `json:"diameter"`
	Type SatelliteType `json:"type"`
	Orbit interface{} `json:"orbit"`
	JSON satelliteJSON `json:"-"`
}

// satelliteJSON contains the JSON metadata for the struct [Satellite]
type satelliteJSON struct {
	Name apijson.Field
	ID apijson.Field
	Description apijson.Field
	Diameter apijson.Field
	Type apijson.Field
	Orbit apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Satellite) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r satelliteJSON) RawJSON() string {
	return r.raw
}

type SatelliteParam struct {
	Name param.Field[string] `json:"name" api:"required"`
	Description param.Field[string] `json:"description"`
	// Diameter in kilometers
	Diameter param.Field[float64] `json:"diameter"`
	Orbit param.Field[interface{}] `json:"orbit"`
	Type param.Field[SatelliteType] `json:"type"`
}

func (r SatelliteParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type SatelliteType string

const (
	SatelliteTypeMoon SatelliteType = "moon"
	SatelliteTypeAsteroid SatelliteType = "asteroid"
	SatelliteTypeComet SatelliteType = "comet"
)

func (r SatelliteType) IsKnown() bool {
	switch r {
	case SatelliteTypeMoon, SatelliteTypeAsteroid, SatelliteTypeComet:
		return true
	}
	return false
}

type PlanetListAllDataResponse struct {
	Data []interface{} `json:"data"`
	Meta PlanetListAllDataResponseMeta `json:"meta"`
	JSON planetListAllDataResponseJSON `json:"-"`
}

// planetListAllDataResponseJSON contains the JSON metadata for the struct [PlanetListAllDataResponse]
type planetListAllDataResponseJSON struct {
	Data apijson.Field
	Meta apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PlanetListAllDataResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r planetListAllDataResponseJSON) RawJSON() string {
	return r.raw
}

type PlanetListAllDataParams struct {
	// The number of items to return
	Limit param.Field[int64] `query:"limit"`
	// The number of items to skip before starting to collect the result set
	Offset param.Field[int64] `query:"offset"`
}

// URLQuery serializes [PlanetListAllDataParams]'s query parameters as `url.Values`.
func (r PlanetListAllDataParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type PlanetNewParams struct {
	Planet PlanetParam `json:"planet" api:"required"`
}

func (r PlanetNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.Planet)
}

type PlanetUpdateParams struct {
	Planet PlanetParam `json:"planet" api:"required"`
}

func (r PlanetUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.Planet)
}

type PlanetUploadImageParams struct {
	// The image file to upload
	Image param.Field[io.Reader] `json:"image" format:"binary"`
}

func (r PlanetUploadImageParams) MarshalMultipart() (data []byte, contentType string, err error) {
	buf := bytes.NewBuffer(nil)
	writer := multipart.NewWriter(buf)
	err = apiform.MarshalRoot(r, writer)
	if err != nil {
		writer.Close()
		return nil, "", err
	}
	err = writer.Close()
	if err != nil {
		return nil, "", err
	}
	return buf.Bytes(), writer.FormDataContentType(), nil
}

type PlanetPhysicalPropertiesParam struct {
	// Surface gravity in Earth g
	Gravity param.Field[float64] `json:"gravity"`
	// Mass in Earth masses (must be greater than 0)
	Mass param.Field[float64] `json:"mass"`
	// Radius in Earth radii (must be greater than 0)
	Radius param.Field[float64] `json:"radius"`
	Temperature param.Field[PlanetPhysicalPropertiesTemperatureParam] `json:"temperature"`
}

func (r PlanetPhysicalPropertiesParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type PlanetAtmosphereParam struct {
	Compound param.Field[string] `json:"compound"`
	Percentage param.Field[float64] `json:"percentage"`
}

func (r PlanetAtmosphereParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type PlanetListAllDataResponseMeta struct {
	Limit int64 `json:"limit"`
	Offset int64 `json:"offset"`
	Total int64 `json:"total"`
	Next string `json:"next" api:"nullable"`
	JSON planetListAllDataResponseMetaJSON `json:"-"`
}

// planetListAllDataResponseMetaJSON contains the JSON metadata for the struct [PlanetListAllDataResponseMeta]
type planetListAllDataResponseMetaJSON struct {
	Limit apijson.Field
	Offset apijson.Field
	Total apijson.Field
	Next apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PlanetListAllDataResponseMeta) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r planetListAllDataResponseMetaJSON) RawJSON() string {
	return r.raw
}

type PlanetUploadImageResponse struct {
	Message string `json:"message"`
	// The URL where the uploaded image can be accessed
	ImageURL string `json:"imageUrl"`
	// Timestamp when the image was uploaded
	UploadedAt time.Time `json:"uploadedAt" format:"date-time"`
	// Size of the uploaded image in bytes
	FileSize int64 `json:"fileSize"`
	// The content type of the uploaded image
	MimeType string `json:"mimeType"`
	JSON planetUploadImageResponseJSON `json:"-"`
}

// planetUploadImageResponseJSON contains the JSON metadata for the struct [PlanetUploadImageResponse]
type planetUploadImageResponseJSON struct {
	Message apijson.Field
	ImageURL apijson.Field
	UploadedAt apijson.Field
	FileSize apijson.Field
	MimeType apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PlanetUploadImageResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r planetUploadImageResponseJSON) RawJSON() string {
	return r.raw
}

type PlanetPhysicalProperties struct {
	// Mass in Earth masses (must be greater than 0)
	Mass float64 `json:"mass"`
	// Radius in Earth radii (must be greater than 0)
	Radius float64 `json:"radius"`
	// Surface gravity in Earth g
	Gravity float64 `json:"gravity"`
	Temperature PlanetPhysicalPropertiesTemperature `json:"temperature"`
	JSON planetPhysicalPropertiesJSON `json:"-"`
}

// planetPhysicalPropertiesJSON contains the JSON metadata for the struct [PlanetPhysicalProperties]
type planetPhysicalPropertiesJSON struct {
	Mass apijson.Field
	Radius apijson.Field
	Gravity apijson.Field
	Temperature apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PlanetPhysicalProperties) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r planetPhysicalPropertiesJSON) RawJSON() string {
	return r.raw
}

type PlanetAtmosphere struct {
	Compound string `json:"compound"`
	Percentage float64 `json:"percentage"`
	JSON planetAtmosphereJSON `json:"-"`
}

// planetAtmosphereJSON contains the JSON metadata for the struct [PlanetAtmosphere]
type planetAtmosphereJSON struct {
	Compound apijson.Field
	Percentage apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PlanetAtmosphere) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r planetAtmosphereJSON) RawJSON() string {
	return r.raw
}

type PlanetPhysicalPropertiesTemperatureParam struct {
	// Average temperature in Kelvin
	Average param.Field[float64] `json:"average"`
	// Maximum temperature in Kelvin
	Max param.Field[float64] `json:"max"`
	// Minimum temperature in Kelvin
	Min param.Field[float64] `json:"min"`
}

func (r PlanetPhysicalPropertiesTemperatureParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type PlanetPhysicalPropertiesTemperature struct {
	// Minimum temperature in Kelvin
	Min float64 `json:"min"`
	// Maximum temperature in Kelvin
	Max float64 `json:"max"`
	// Average temperature in Kelvin
	Average float64 `json:"average"`
	JSON planetPhysicalPropertiesTemperatureJSON `json:"-"`
}

// planetPhysicalPropertiesTemperatureJSON contains the JSON metadata for the struct [PlanetPhysicalPropertiesTemperature]
type planetPhysicalPropertiesTemperatureJSON struct {
	Min apijson.Field
	Max apijson.Field
	Average apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PlanetPhysicalPropertiesTemperature) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r planetPhysicalPropertiesTemperatureJSON) RawJSON() string {
	return r.raw
}
