// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalargalaxy

import (
	"errors"
	"net/http"
	"slices"
	"time"

	standardwebhooks "github.com/standard-webhooks/standard-webhooks/libraries/go"

	"github.com/scalar/galaxy-go/internal/apijson"
	"github.com/scalar/galaxy-go/internal/requestconfig"
	"github.com/scalar/galaxy-go/option"
)

// WebhookService contains methods that help with parsing and verifying inbound
// webhook payloads. You should not instantiate this service directly, and
// instead use the [NewWebhookService] method instead.
type WebhookService struct {
	Options []option.RequestOption
}

// NewWebhookService generates a new service that applies the given options to each
// request. These options are applied after the parent client's options (if there
// is one), and before any request-specific options.
func NewWebhookService(opts ...option.RequestOption) (r *WebhookService) {
	r = &WebhookService{}
	r.Options = opts
	return
}

// Parsed verifies the webhook signature using the WebhookSecret option (set on the
// client or per call) and decodes the payload into a [ParsedWebhookEvent].
func (r *WebhookService) Parsed(payload []byte, headers http.Header, opts ...option.RequestOption) (*ParsedWebhookEvent, error) {
	opts = slices.Concat(r.Options, opts)
	cfg, err := requestconfig.PreRequestOptions(opts...)
	if err != nil {
		return nil, err
	}
	key := cfg.WebhookSecret
	if key == "" {
		return nil, errors.New("The WebhookSecret option must be set in order to verify webhook headers")
	}
	wh, err := standardwebhooks.NewWebhook(key)
	if err != nil {
		return nil, err
	}
	err = wh.Verify(payload, headers)
	if err != nil {
		return nil, err
	}
	res := &ParsedWebhookEvent{}
	err = res.UnmarshalJSON(payload)
	if err != nil {
		return res, err
	}
	return res, nil
}

type NewPlanetWebhookEvent struct {
	ID          int64                     `json:"id" api:"required"`
	Name        string                    `json:"name" api:"required"`
	Description string                    `json:"description" api:"nullable"`
	Type        NewPlanetWebhookEventType `json:"type"`
	// A score from 0 to 1 indicating potential habitability
	HabitabilityIndex  float64                                 `json:"habitabilityIndex"`
	PhysicalProperties NewPlanetWebhookEventPhysicalProperties `json:"physicalProperties"`
	// Atmospheric composition
	Atmosphere   []NewPlanetWebhookEventAtmosphere `json:"atmosphere"`
	DiscoveredAt time.Time                         `json:"discoveredAt" format:"date-time"`
	Image        string                            `json:"image" api:"nullable"`
	Satellites   []NewPlanetWebhookEventSatellite  `json:"satellites"`
	// A user
	Creator     User      `json:"creator"`
	Tags        []string  `json:"tags"`
	LastUpdated time.Time `json:"lastUpdated" format:"date-time"`
	// URL which gets invoked upon a successful operation
	SuccessCallbackURL string `json:"successCallbackUrl" format:"uri"`
	// URL which gets invoked upon a failed operation
	FailureCallbackURL string                    `json:"failureCallbackUrl" format:"uri"`
	JSON               newPlanetWebhookEventJSON `json:"-"`
}

// newPlanetWebhookEventJSON contains the JSON metadata for the struct [NewPlanetWebhookEvent]
type newPlanetWebhookEventJSON struct {
	ID                 apijson.Field
	Name               apijson.Field
	Description        apijson.Field
	Type               apijson.Field
	HabitabilityIndex  apijson.Field
	PhysicalProperties apijson.Field
	Atmosphere         apijson.Field
	DiscoveredAt       apijson.Field
	Image              apijson.Field
	Satellites         apijson.Field
	Creator            apijson.Field
	Tags               apijson.Field
	LastUpdated        apijson.Field
	SuccessCallbackURL apijson.Field
	FailureCallbackURL apijson.Field
	raw                string
	ExtraFields        map[string]apijson.Field
}

func (r *NewPlanetWebhookEvent) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r newPlanetWebhookEventJSON) RawJSON() string {
	return r.raw
}

type NewPlanetWebhookEventType string

const (
	NewPlanetWebhookEventTypeTerrestrial NewPlanetWebhookEventType = "terrestrial"
	NewPlanetWebhookEventTypeGasGiant    NewPlanetWebhookEventType = "gas_giant"
	NewPlanetWebhookEventTypeIceGiant    NewPlanetWebhookEventType = "ice_giant"
	NewPlanetWebhookEventTypeDwarf       NewPlanetWebhookEventType = "dwarf"
	NewPlanetWebhookEventTypeSuperEarth  NewPlanetWebhookEventType = "super_earth"
)

func (r NewPlanetWebhookEventType) IsKnown() bool {
	switch r {
	case NewPlanetWebhookEventTypeTerrestrial, NewPlanetWebhookEventTypeGasGiant, NewPlanetWebhookEventTypeIceGiant, NewPlanetWebhookEventTypeDwarf, NewPlanetWebhookEventTypeSuperEarth:
		return true
	}
	return false
}

type NewPlanetWebhookEventPhysicalProperties struct {
	// Mass in Earth masses (must be greater than 0)
	Mass float64 `json:"mass"`
	// Radius in Earth radii (must be greater than 0)
	Radius float64 `json:"radius"`
	// Surface gravity in Earth g
	Gravity     float64                                            `json:"gravity"`
	Temperature NewPlanetWebhookEventPhysicalPropertiesTemperature `json:"temperature"`
	JSON        newPlanetWebhookEventPhysicalPropertiesJSON        `json:"-"`
}

// newPlanetWebhookEventPhysicalPropertiesJSON contains the JSON metadata for the struct [NewPlanetWebhookEventPhysicalProperties]
type newPlanetWebhookEventPhysicalPropertiesJSON struct {
	Mass        apijson.Field
	Radius      apijson.Field
	Gravity     apijson.Field
	Temperature apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *NewPlanetWebhookEventPhysicalProperties) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r newPlanetWebhookEventPhysicalPropertiesJSON) RawJSON() string {
	return r.raw
}

type NewPlanetWebhookEventPhysicalPropertiesTemperature struct {
	// Minimum temperature in Kelvin
	Min float64 `json:"min"`
	// Maximum temperature in Kelvin
	Max float64 `json:"max"`
	// Average temperature in Kelvin
	Average float64                                                `json:"average"`
	JSON    newPlanetWebhookEventPhysicalPropertiesTemperatureJSON `json:"-"`
}

// newPlanetWebhookEventPhysicalPropertiesTemperatureJSON contains the JSON metadata for the struct [NewPlanetWebhookEventPhysicalPropertiesTemperature]
type newPlanetWebhookEventPhysicalPropertiesTemperatureJSON struct {
	Min         apijson.Field
	Max         apijson.Field
	Average     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *NewPlanetWebhookEventPhysicalPropertiesTemperature) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r newPlanetWebhookEventPhysicalPropertiesTemperatureJSON) RawJSON() string {
	return r.raw
}

type NewPlanetWebhookEventAtmosphere struct {
	Compound   string                              `json:"compound"`
	Percentage float64                             `json:"percentage"`
	JSON       newPlanetWebhookEventAtmosphereJSON `json:"-"`
}

// newPlanetWebhookEventAtmosphereJSON contains the JSON metadata for the struct [NewPlanetWebhookEventAtmosphere]
type newPlanetWebhookEventAtmosphereJSON struct {
	Compound    apijson.Field
	Percentage  apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *NewPlanetWebhookEventAtmosphere) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r newPlanetWebhookEventAtmosphereJSON) RawJSON() string {
	return r.raw
}

type NewPlanetWebhookEventSatellite struct {
	Name        string `json:"name" api:"required"`
	ID          int64  `json:"id"`
	Description string `json:"description" api:"nullable"`
	// Diameter in kilometers
	Diameter float64                             `json:"diameter"`
	Type     NewPlanetWebhookEventSatellitesType `json:"type"`
	Orbit    interface{}                         `json:"orbit"`
	JSON     newPlanetWebhookEventSatelliteJSON  `json:"-"`
}

// newPlanetWebhookEventSatelliteJSON contains the JSON metadata for the struct [NewPlanetWebhookEventSatellite]
type newPlanetWebhookEventSatelliteJSON struct {
	Name        apijson.Field
	ID          apijson.Field
	Description apijson.Field
	Diameter    apijson.Field
	Type        apijson.Field
	Orbit       apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *NewPlanetWebhookEventSatellite) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r newPlanetWebhookEventSatelliteJSON) RawJSON() string {
	return r.raw
}

type NewPlanetWebhookEventSatellitesType string

const (
	NewPlanetWebhookEventSatellitesTypeMoon     NewPlanetWebhookEventSatellitesType = "moon"
	NewPlanetWebhookEventSatellitesTypeAsteroid NewPlanetWebhookEventSatellitesType = "asteroid"
	NewPlanetWebhookEventSatellitesTypeComet    NewPlanetWebhookEventSatellitesType = "comet"
)

func (r NewPlanetWebhookEventSatellitesType) IsKnown() bool {
	switch r {
	case NewPlanetWebhookEventSatellitesTypeMoon, NewPlanetWebhookEventSatellitesTypeAsteroid, NewPlanetWebhookEventSatellitesTypeComet:
		return true
	}
	return false
}

type ParsedWebhookEvent struct {
	ID          int64                  `json:"id" api:"required"`
	Name        string                 `json:"name" api:"required"`
	Description string                 `json:"description" api:"nullable"`
	Type        ParsedWebhookEventType `json:"type"`
	// A score from 0 to 1 indicating potential habitability
	HabitabilityIndex  float64                                 `json:"habitabilityIndex"`
	PhysicalProperties NewPlanetWebhookEventPhysicalProperties `json:"physicalProperties"`
	// Atmospheric composition
	Atmosphere   []NewPlanetWebhookEventAtmosphere `json:"atmosphere"`
	DiscoveredAt time.Time                         `json:"discoveredAt" format:"date-time"`
	Image        string                            `json:"image" api:"nullable"`
	Satellites   []NewPlanetWebhookEventSatellite  `json:"satellites"`
	// A user
	Creator     User      `json:"creator"`
	Tags        []string  `json:"tags"`
	LastUpdated time.Time `json:"lastUpdated" format:"date-time"`
	// URL which gets invoked upon a successful operation
	SuccessCallbackURL string `json:"successCallbackUrl" format:"uri"`
	// URL which gets invoked upon a failed operation
	FailureCallbackURL string                 `json:"failureCallbackUrl" format:"uri"`
	JSON               parsedWebhookEventJSON `json:"-"`
}

// parsedWebhookEventJSON contains the JSON metadata for the struct [ParsedWebhookEvent]
type parsedWebhookEventJSON struct {
	ID                 apijson.Field
	Name               apijson.Field
	Description        apijson.Field
	Type               apijson.Field
	HabitabilityIndex  apijson.Field
	PhysicalProperties apijson.Field
	Atmosphere         apijson.Field
	DiscoveredAt       apijson.Field
	Image              apijson.Field
	Satellites         apijson.Field
	Creator            apijson.Field
	Tags               apijson.Field
	LastUpdated        apijson.Field
	SuccessCallbackURL apijson.Field
	FailureCallbackURL apijson.Field
	raw                string
	ExtraFields        map[string]apijson.Field
}

func (r *ParsedWebhookEvent) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r parsedWebhookEventJSON) RawJSON() string {
	return r.raw
}

type ParsedWebhookEventType string

const (
	ParsedWebhookEventTypeTerrestrial ParsedWebhookEventType = "terrestrial"
	ParsedWebhookEventTypeGasGiant    ParsedWebhookEventType = "gas_giant"
	ParsedWebhookEventTypeIceGiant    ParsedWebhookEventType = "ice_giant"
	ParsedWebhookEventTypeDwarf       ParsedWebhookEventType = "dwarf"
	ParsedWebhookEventTypeSuperEarth  ParsedWebhookEventType = "super_earth"
)

func (r ParsedWebhookEventType) IsKnown() bool {
	switch r {
	case ParsedWebhookEventTypeTerrestrial, ParsedWebhookEventTypeGasGiant, ParsedWebhookEventTypeIceGiant, ParsedWebhookEventTypeDwarf, ParsedWebhookEventTypeSuperEarth:
		return true
	}
	return false
}
