// Code generated by Scalar SDK Generator. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
	"sync"
	"time"

	sdk "github.com/scalar/galaxy-go"
	"github.com/scalar/galaxy-go/option"
)

// Smoke test: calls every generated operation once to confirm the SDK can reach each endpoint.
// Run it from this repo with `go run tests/smoke-test.go`. The generator also runs this file
// against a mock server and reads the JSON report produced via SCALAR_SMOKE_REPORT.
var client = sdk.NewClient(option.WithBearerAuth("test"), option.WithBasicAuthUsername("test"), option.WithBasicAuthPassword("test"), option.WithAPIKeyHeader("test"), option.WithAPIKeyQuery("test"), option.WithAPIKeyCookie("test"), option.WithHeader("X-API-Key", "test"), option.WithHeader("Authorization", "Bearer test"), option.WithHeader("Authorization", "Bearer test"), option.WithHeader("Authorization", "Bearer test"))

type smokeResult struct {
	Operation  string `json:"operation"`
	Method     string `json:"method"`
	Path       string `json:"path"`
	Label      string `json:"label,omitempty"`
	Status     string `json:"status"`
	DurationMs int64  `json:"durationMs"`
	Error      string `json:"error,omitempty"`
}

// Label says which of an operation's two calls this is — "required params" or "all params".
// It is empty when the operation contributed a single case.
type smokeCase struct {
	Operation string
	Method    string
	Path      string
	Label     string
	Run       func()
}

func _smokeCase0() {
	planet, err := client.Planets.ListAllData(context.Background(), sdk.PlanetListAllDataParams{
		Limit:  sdk.F[int64](10),
		Offset: sdk.F[int64](0),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(planet)
}

func _smokeCase1() {
	planet, err := client.Planets.New(context.Background(), sdk.PlanetNewParams{
		Planet: sdk.PlanetParam{
			Name: sdk.F[string]("Mars"),
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(planet)
}

func _smokeCase2() {
	planet, err := client.Planets.New(context.Background(), sdk.PlanetNewParams{
		Planet: sdk.PlanetParam{
			Name:               sdk.F[string]("Mars"),
			Description:        sdk.F[string]("The red planet"),
			HabitabilityIndex:  sdk.F[float64](0.68),
			PhysicalProperties: sdk.F[sdk.PlanetPhysicalPropertiesParam](sdk.PlanetPhysicalPropertiesParam{}),
			Atmosphere:         sdk.F[[]sdk.PlanetAtmosphereParam]([]sdk.PlanetAtmosphereParam{sdk.PlanetAtmosphereParam{}}),
			DiscoveredAt:       sdk.F[time.Time](time.Now()),
			Image:              sdk.F[string]("https://cdn.scalar.com/photos/mars.jpg"),
			Creator:            sdk.F[sdk.UserParam](sdk.UserParam{}),
			Tags:               sdk.F[[]string]([]string{""}),
			SuccessCallbackURL: sdk.F[string]("https://example.com/webhook"),
			FailureCallbackURL: sdk.F[string]("https://example.com/webhook"),
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(planet)
}

func _smokeCase3() {
	planet, err := client.Planets.Get(context.Background(), 1)
	if err != nil {
		panic(err)
	}

	fmt.Println(planet)
}

func _smokeCase4() {
	planet, err := client.Planets.Update(context.Background(), 1, sdk.PlanetUpdateParams{
		Planet: sdk.PlanetParam{
			Name: sdk.F[string]("Mars"),
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(planet)
}

func _smokeCase5() {
	planet, err := client.Planets.Update(context.Background(), 1, sdk.PlanetUpdateParams{
		Planet: sdk.PlanetParam{
			Name:               sdk.F[string]("Mars"),
			Description:        sdk.F[string]("The red planet"),
			HabitabilityIndex:  sdk.F[float64](0.68),
			PhysicalProperties: sdk.F[sdk.PlanetPhysicalPropertiesParam](sdk.PlanetPhysicalPropertiesParam{}),
			Atmosphere:         sdk.F[[]sdk.PlanetAtmosphereParam]([]sdk.PlanetAtmosphereParam{sdk.PlanetAtmosphereParam{}}),
			DiscoveredAt:       sdk.F[time.Time](time.Now()),
			Image:              sdk.F[string]("https://cdn.scalar.com/photos/mars.jpg"),
			Creator:            sdk.F[sdk.UserParam](sdk.UserParam{}),
			Tags:               sdk.F[[]string]([]string{""}),
			SuccessCallbackURL: sdk.F[string]("https://example.com/webhook"),
			FailureCallbackURL: sdk.F[string]("https://example.com/webhook"),
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(planet)
}

func _smokeCase6() {
	err := client.Planets.Delete(context.Background(), 1)
	if err != nil {
		panic(err)
	}
}

func _smokeCase7() {
	planet, err := client.Planets.DelteImage(context.Background(), 1, sdk.PlanetDelteImageParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(planet)
}

func _smokeCase8() {
	planet, err := client.Planets.DelteImage(context.Background(), 1, sdk.PlanetDelteImageParams{
		Image: sdk.F[io.Reader](strings.NewReader("")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(planet)
}

func _smokeCase9() {
	celestialBody, err := client.CelestialBodies.New(context.Background(), sdk.CelestialBodyNewParams{
		CelestialBody: sdk.PlanetParam{
			Name: sdk.F[string]("Mars"),
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(celestialBody)
}

func _smokeCase10() {
	authentication, err := client.Authentication.NewUser(context.Background(), sdk.AuthenticationNewUserParams{
		Email:    sdk.F[string]("marc@scalar.com"),
		Password: sdk.F[string]("i-love-scalar"),
		Name:     sdk.F[string]("Marc"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(authentication)
}

func _smokeCase11() {
	authentication, err := client.Authentication.NewToken(context.Background(), sdk.AuthenticationNewTokenParams{
		Credentials: sdk.CredentialsParam{
			Email:    sdk.F[string]("marc@scalar.com"),
			Password: sdk.F[string]("i-love-scalar"),
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(authentication)
}

func _smokeCase12() {
	authentication, err := client.Authentication.ListMe(context.Background())
	if err != nil {
		panic(err)
	}

	fmt.Println(authentication)
}

var cases = []smokeCase{
	{
		Operation: "listAllData",
		Method:    "GET",
		Path:      "/planets",
		Run:       _smokeCase0,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/planets",
		Label:     "required params",
		Run:       _smokeCase1,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/planets",
		Label:     "all params",
		Run:       _smokeCase2,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/planets/{planetId}",
		Run:       _smokeCase3,
	},

	{
		Operation: "update",
		Method:    "PUT",
		Path:      "/planets/{planetId}",
		Label:     "required params",
		Run:       _smokeCase4,
	},

	{
		Operation: "update",
		Method:    "PUT",
		Path:      "/planets/{planetId}",
		Label:     "all params",
		Run:       _smokeCase5,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/planets/{planetId}",
		Run:       _smokeCase6,
	},

	{
		Operation: "delteImage",
		Method:    "POST",
		Path:      "/planets/{planetId}/image",
		Label:     "required params",
		Run:       _smokeCase7,
	},

	{
		Operation: "delteImage",
		Method:    "POST",
		Path:      "/planets/{planetId}/image",
		Label:     "all params",
		Run:       _smokeCase8,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/celestial-bodies",
		Run:       _smokeCase9,
	},

	{
		Operation: "createUser",
		Method:    "POST",
		Path:      "/user/signup",
		Run:       _smokeCase10,
	},

	{
		Operation: "createToken",
		Method:    "POST",
		Path:      "/auth/token",
		Run:       _smokeCase11,
	},

	{
		Operation: "listMe",
		Method:    "GET",
		Path:      "/me",
		Run:       _smokeCase12,
	},
}

func selectedCases() []smokeCase {
	filter := os.Getenv("SCALAR_SMOKE_FILTER")
	if filter == "" {
		return cases
	}
	needles := strings.Split(filter, ",")
	selected := make([]smokeCase, 0, len(cases))
	for _, testCase := range cases {
		for _, needle := range needles {
			needle = strings.TrimSpace(needle)
			if needle == "" {
				continue
			}
			if strings.Contains(testCase.Operation, needle) || strings.Contains(testCase.Path, needle) {
				selected = append(selected, testCase)
				break
			}
		}
	}
	return selected
}

func runCase(testCase smokeCase) (result smokeResult) {
	startedAt := time.Now()
	result = smokeResult{
		Operation: testCase.Operation,
		Method:    testCase.Method,
		Path:      testCase.Path,
		Label:     testCase.Label,
		Status:    "passed",
	}
	defer func() {
		result.DurationMs = time.Since(startedAt).Milliseconds()
		if recovered := recover(); recovered != nil {
			result.Status = "failed"
			result.Error = fmt.Sprint(recovered)
		}
	}()
	testCase.Run()
	return result
}

func main() {
	selected := selectedCases()
	results := make([]smokeResult, len(selected))
	var wg sync.WaitGroup
	for index, testCase := range selected {
		wg.Add(1)
		go func(index int, testCase smokeCase) {
			defer wg.Done()
			results[index] = runCase(testCase)
		}(index, testCase)
	}
	wg.Wait()

	failed := 0
	for _, result := range results {
		if result.Status == "failed" {
			failed++
		}
	}

	report := map[string]interface{}{"total": len(results), "failed": failed, "results": results}
	if reportPath := os.Getenv("SCALAR_SMOKE_REPORT"); reportPath != "" {
		bytes, err := json.Marshal(report)
		if err != nil {
			panic(err)
		}
		if err := os.WriteFile(reportPath, bytes, 0o644); err != nil {
			panic(err)
		}
	} else {
		for _, result := range results {
			suffix := ""
			if result.Label != "" {
				suffix = " [" + result.Label + "]"
			}
			if result.Status == "passed" {
				fmt.Printf("PASS %s%s (%s %s) %dms\n", result.Operation, suffix, result.Method, result.Path, result.DurationMs)
			} else {
				fmt.Fprintf(os.Stderr, "FAIL %s%s (%s %s)\n%s\n", result.Operation, suffix, result.Method, result.Path, result.Error)
			}
		}
		if len(results) == 0 {
			fmt.Fprintln(os.Stderr, "No code samples ran (empty SDK or a SCALAR_SMOKE_FILTER that matched nothing).")
		} else {
			fmt.Printf("\n%d/%d samples passed\n", len(results)-failed, len(results))
		}
	}

	if failed > 0 || len(results) == 0 {
		os.Exit(1)
	}
}
